# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='description',
        ),
    ]
