# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170316_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='heading_1_title',
            field=models.CharField(max_length=128, null=True, verbose_name='Left Heading Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_2_title',
            field=models.CharField(max_length=128, null=True, verbose_name='Center Heading Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_3_title',
            field=models.CharField(max_length=128, null=True, verbose_name='Right Heading Title'),
        ),
    ]
