# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 22:34
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170316_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_images',
            field=wagtail.wagtailcore.fields.StreamField((('header_image', wagtail.wagtailimages.blocks.ImageChooserBlock()),), help_text='Make sure you have exactly 2 header images for this page.', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='headers',
            field=wagtail.wagtailcore.fields.StreamField((('header', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('description', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('link', wagtail.wagtailcore.blocks.URLBlock(required=True))))),), help_text='Make sure you have exactly 3 headers for this page.', null=True),
        ),
    ]
