# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170319_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('address_1', models.CharField(blank=True, max_length=128, null=True)),
                ('address_2', models.CharField(blank=True, max_length=128, null=True)),
                ('address_3', models.CharField(blank=True, max_length=128, null=True)),
                ('address_4', models.CharField(blank=True, max_length=128, null=True)),
                ('additional_text_1', models.CharField(blank=True, max_length=128, null=True)),
                ('additional_text_2', models.CharField(blank=True, max_length=128, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('google', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
