# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0012_videopage_videopagegalleryvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopagegalleryvideo',
            name='splash_image',
            field=models.ForeignKey(blank=True, help_text='If provided, will be used as the splash image before the video starts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='videopagegalleryvideo',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, help_text='If provided, will be used as the thumbnail at the bottom of the video player.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
