# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 01:00
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_contactuspage_thank_you_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content_sections',
            field=wagtail.wagtailcore.fields.StreamField((('sections', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('description', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('link', wagtail.wagtailcore.blocks.URLBlock(required=False))))),), null=True),
        ),
    ]
