# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170414_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='bottom_section_header',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='bottom_section_link',
            field=models.CharField(blank=True, help_text='Name of page to link to. Example: services', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='bottom_section_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
