# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20170501_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitefooter',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
